### ISSUE TITLE
The command in README need to be modified

### ISSUE THREAD

**Issue by fxbing** [streamnative/apache-pulsar-grafana-dashboard#16]
`
ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{ print $2 }
`

I 'm running this command in Ubuntu 16.04 , the result is

`addr:172.17.0.1 `
 `addr:192.168.247.129`.

It doesn't just contain ip.

**Comment by sijie** [comment]
@fxbing do you mind fixing the issue?

**Comment by fxbing** [comment]
> @fxbing do you mind fixing the issue?

`ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{ print $2 }' | awk -F ':' '{ print $2 }' | awk 'NR==2'`
This command can get correct result in my machine. 
But it depending on number and order of network interfaces. 
So I suggest to set it manually.

**Comment by sijie** [comment]
@fxbing sgtm. maybe we can update the README?
