### ISSUE TITLE
bookie_journal_JOURNAL_QUEUE_SIZE is  negative number

### ISSUE THREAD

**Issue by 4onni** [streamnative/apache-pulsar-grafana-dashboard#57]
Dashboard:
![image](https://user-images.githubusercontent.com/5661665/98660152-f00af200-237f-11eb-837b-06da9772e7c8.png)

**Comment by sijie** [comment]
@4onni It is a problem in bookkeeper. Can you help create an issue at https://github.com/apache/bookkeeper?

**Comment by 4onni** [comment]
> @4onni It is a problem in bookkeeper. Can you help create an issue at https://github.com/apache/bookkeeper?

Ok. https://github.com/apache/bookkeeper/issues/2483
